---
# tasks file for mysql

- name: Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password password {{ mysql_root_password }} | sudo /usr/bin/debconf-set-selections

- name: Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password_again password {{ mysql_root_password }} | sudo /usr/bin/debconf-set-selections

- name: Install mysql database
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
      - python-mysqldb
      - mysql-client
      - mysql-server

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=~/.my.cnf mode=0600
  notify:
   - restart mysql

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} login_user=root login_password={{ mysql_root_password }} check_implicit_admin=yes
  with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
      - localhost
      - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent

- name: Create Database
  action: mysql_db login_user=root login_password={{ mysql_root_password }} name="{{ item.name }}"
  with_items:  mysql_users
  when:  mysql_users is defined

- name: Adds required MySQL users
  mysql_user: login_user=root login_password={{ mysql_root_password }} user="{{ item.name }}" password="{{ item.password }}" priv="{{ item.privs }}"
  with_items:  mysql_users
  when:  mysql_users is defined
